spring.application.name=flyaway
server.port=8080

spring.datasource.url=jdbc:h2:mem:flyawaydb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=ZmF5LWF3YXktdHJhdmVsLXN1cGVyLXNlY3JldC1qd3Qta2V5LWZvci1oczI1Ni1zaWduaW5nLTIwMjY=
app.jwt.expiration-ms=86400000

app.email.directory=./emails
